### ISSUE TITLE
Step 7: Call pack_padded_sequence with embeded instances and sequence lengths

### ISSUE THREAD

**Issue by lezhang-thu** [HarshTrivedi/packing-unpacking-pytorch-minimal-tutorial#4]
The comment for `packed_input.data` should be characters `l, m, t` etc., rather than `l, o, n` etc.
Am I right?
(Thanks for the tutorial shown here. It helps me a lot.)

**Comment by HarshTrivedi** [comment]
Hi @lezhang-thu ! Yes, order should be the one you mentioned. But also note that vectors commented for `packed_input.data` also seem to be incorrect.  They should be `18 X 4` taking values from `embedded_seq_tensor ` in the order that you mention. Currently, it is shown as `18 X 5` (copy of `packed_output.data`). I will fix it in few days.
